# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 782)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.LeftTab = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LeftTab.sizePolicy().hasHeightForWidth())
        self.LeftTab.setSizePolicy(sizePolicy)
        self.LeftTab.setObjectName("LeftTab")
        self.LocalTab = QtWidgets.QWidget()
        self.LocalTab.setObjectName("LocalTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.LocalTab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.LocalDirBut = QtWidgets.QPushButton(self.LocalTab)
        self.LocalDirBut.setObjectName("LocalDirBut")
        self.gridLayout_3.addWidget(self.LocalDirBut, 0, 0, 1, 1)
        self.LocalTableL = QtWidgets.QTableView(self.LocalTab)
        self.LocalTableL.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.LocalTableL.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.LocalTableL.setObjectName("LocalTableL")
        self.LocalTableL.verticalHeader().setVisible(False)
        self.LocalTableL.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_3.addWidget(self.LocalTableL, 1, 0, 1, 3)
        self.LocalQuickRefreshButton = QtWidgets.QPushButton(self.LocalTab)
        self.LocalQuickRefreshButton.setObjectName("LocalQuickRefreshButton")
        self.gridLayout_3.addWidget(self.LocalQuickRefreshButton, 0, 1, 1, 1)
        self.LocalFullRefreshButton = QtWidgets.QPushButton(self.LocalTab)
        self.LocalFullRefreshButton.setObjectName("LocalFullRefreshButton")
        self.gridLayout_3.addWidget(self.LocalFullRefreshButton, 0, 2, 1, 1)
        self.LeftTab.addTab(self.LocalTab, "")
        self.RemoteTab = QtWidgets.QWidget()
        self.RemoteTab.setObjectName("RemoteTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.RemoteTab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.RemoteTableL = QtWidgets.QTableView(self.RemoteTab)
        self.RemoteTableL.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.RemoteTableL.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.RemoteTableL.setObjectName("RemoteTableL")
        self.RemoteTableL.verticalHeader().setVisible(False)
        self.RemoteTableL.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_2.addWidget(self.RemoteTableL, 1, 0, 1, 3)
        self.LocalDirBut_2 = QtWidgets.QPushButton(self.RemoteTab)
        self.LocalDirBut_2.setObjectName("LocalDirBut_2")
        self.gridLayout_2.addWidget(self.LocalDirBut_2, 0, 0, 1, 1)
        self.RemoteQuickRefreshButton2 = QtWidgets.QPushButton(self.RemoteTab)
        self.RemoteQuickRefreshButton2.setObjectName("RemoteQuickRefreshButton2")
        self.gridLayout_2.addWidget(self.RemoteQuickRefreshButton2, 0, 1, 1, 1)
        self.RemoteFullRefreshButton2 = QtWidgets.QPushButton(self.RemoteTab)
        self.RemoteFullRefreshButton2.setObjectName("RemoteFullRefreshButton2")
        self.gridLayout_2.addWidget(self.RemoteFullRefreshButton2, 0, 2, 1, 1)
        self.LeftTab.addTab(self.RemoteTab, "")
        self.PlaylistTab = QtWidgets.QWidget()
        self.PlaylistTab.setObjectName("PlaylistTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.PlaylistTab)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.LeftLoadPlaylistBut = QtWidgets.QPushButton(self.PlaylistTab)
        self.LeftLoadPlaylistBut.setObjectName("LeftLoadPlaylistBut")
        self.gridLayout_4.addWidget(self.LeftLoadPlaylistBut, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.PlaylistTab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.PlaylistTab)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 0, 2, 1, 1)
        self.LeftPlaylistTable = QtWidgets.QTableView(self.PlaylistTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LeftPlaylistTable.sizePolicy().hasHeightForWidth())
        self.LeftPlaylistTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LeftPlaylistTable.setFont(font)
        self.LeftPlaylistTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.LeftPlaylistTable.setObjectName("LeftPlaylistTable")
        self.LeftPlaylistTable.verticalHeader().setVisible(False)
        self.LeftPlaylistTable.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_4.addWidget(self.LeftPlaylistTable, 1, 0, 1, 3)
        self.LeftTab.addTab(self.PlaylistTab, "")
        self.RightTab = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RightTab.sizePolicy().hasHeightForWidth())
        self.RightTab.setSizePolicy(sizePolicy)
        self.RightTab.setObjectName("RightTab")
        self.LocalTab_2 = QtWidgets.QWidget()
        self.LocalTab_2.setObjectName("LocalTab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.LocalTab_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.LocalTableR = QtWidgets.QTableView(self.LocalTab_2)
        self.LocalTableR.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.LocalTableR.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.LocalTableR.setObjectName("LocalTableR")
        self.LocalTableR.verticalHeader().setVisible(False)
        self.LocalTableR.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_5.addWidget(self.LocalTableR, 1, 0, 1, 3)
        self.LocalDirBut_3 = QtWidgets.QPushButton(self.LocalTab_2)
        self.LocalDirBut_3.setObjectName("LocalDirBut_3")
        self.gridLayout_5.addWidget(self.LocalDirBut_3, 0, 0, 1, 1)
        self.LocalQuickRefreshButton2 = QtWidgets.QPushButton(self.LocalTab_2)
        self.LocalQuickRefreshButton2.setObjectName("LocalQuickRefreshButton2")
        self.gridLayout_5.addWidget(self.LocalQuickRefreshButton2, 0, 1, 1, 1)
        self.LocalFullRefreshButton2 = QtWidgets.QPushButton(self.LocalTab_2)
        self.LocalFullRefreshButton2.setObjectName("LocalFullRefreshButton2")
        self.gridLayout_5.addWidget(self.LocalFullRefreshButton2, 0, 2, 1, 1)
        self.RightTab.addTab(self.LocalTab_2, "")
        self.RemoteTab_2 = QtWidgets.QWidget()
        self.RemoteTab_2.setObjectName("RemoteTab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.RemoteTab_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.RemoteTableR = QtWidgets.QTableView(self.RemoteTab_2)
        self.RemoteTableR.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.RemoteTableR.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.RemoteTableR.setObjectName("RemoteTableR")
        self.RemoteTableR.verticalHeader().setVisible(False)
        self.RemoteTableR.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_6.addWidget(self.RemoteTableR, 1, 0, 1, 3)
        self.LocalDirBut_4 = QtWidgets.QPushButton(self.RemoteTab_2)
        self.LocalDirBut_4.setObjectName("LocalDirBut_4")
        self.gridLayout_6.addWidget(self.LocalDirBut_4, 0, 0, 1, 1)
        self.RemoteQuickRefreshButton = QtWidgets.QPushButton(self.RemoteTab_2)
        self.RemoteQuickRefreshButton.setObjectName("RemoteQuickRefreshButton")
        self.gridLayout_6.addWidget(self.RemoteQuickRefreshButton, 0, 1, 1, 1)
        self.RemoteFullRefreshButton = QtWidgets.QPushButton(self.RemoteTab_2)
        self.RemoteFullRefreshButton.setObjectName("RemoteFullRefreshButton")
        self.gridLayout_6.addWidget(self.RemoteFullRefreshButton, 0, 2, 1, 1)
        self.RightTab.addTab(self.RemoteTab_2, "")
        self.PlaylistTab_2 = QtWidgets.QWidget()
        self.PlaylistTab_2.setObjectName("PlaylistTab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.PlaylistTab_2)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_7 = QtWidgets.QPushButton(self.PlaylistTab_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_7.addWidget(self.pushButton_7, 0, 1, 1, 1)
        self.RightLoadPlaylistBut = QtWidgets.QPushButton(self.PlaylistTab_2)
        self.RightLoadPlaylistBut.setObjectName("RightLoadPlaylistBut")
        self.gridLayout_7.addWidget(self.RightLoadPlaylistBut, 0, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.PlaylistTab_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_7.addWidget(self.pushButton_8, 0, 2, 1, 1)
        self.RightPlaylistTable = QtWidgets.QTableView(self.PlaylistTab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RightPlaylistTable.sizePolicy().hasHeightForWidth())
        self.RightPlaylistTable.setSizePolicy(sizePolicy)
        self.RightPlaylistTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.RightPlaylistTable.setObjectName("RightPlaylistTable")
        self.RightPlaylistTable.verticalHeader().setVisible(False)
        self.RightPlaylistTable.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_7.addWidget(self.RightPlaylistTable, 1, 0, 1, 3)
        self.RightTab.addTab(self.PlaylistTab_2, "")
        self.gridLayout.addWidget(self.splitter, 3, 0, 1, 2)
        self.SyncBut = QtWidgets.QPushButton(self.centralwidget)
        self.SyncBut.setObjectName("SyncBut")
        self.gridLayout.addWidget(self.SyncBut, 2, 0, 1, 2)
        self.gridLayout_8.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 21))
        self.menubar.setObjectName("menubar")
        self.menuPJS_Test = QtWidgets.QMenu(self.menubar)
        self.menuPJS_Test.setObjectName("menuPJS_Test")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuPJS_Test.menuAction())

        self.retranslateUi(MainWindow)
        self.LeftTab.setCurrentIndex(1)
        self.RightTab.setCurrentIndex(0)
        self.SyncBut.clicked.connect(MainWindow.sync_files)
        self.LocalDirBut_3.clicked.connect(MainWindow.local_edit_dirs)
        self.LocalDirBut.clicked.connect(MainWindow.local_edit_dirs)
        self.LocalDirBut_2.clicked.connect(MainWindow.remote_edit_dirs)
        self.LocalDirBut_4.clicked.connect(MainWindow.remote_edit_dirs)
        self.LeftLoadPlaylistBut.clicked.connect(MainWindow.left_load_playlist)
        self.RightLoadPlaylistBut.clicked.connect(MainWindow.right_load_playlist)
        self.pushButton_4.clicked.connect(MainWindow.left_save_remote)
        self.pushButton.clicked.connect(MainWindow.left_save_local)
        self.pushButton_8.clicked.connect(MainWindow.right_save_remote)
        self.pushButton_7.clicked.connect(MainWindow.right_save_local)
        self.RemoteTableR.customContextMenuRequested['QPoint'].connect(MainWindow.right_remote_context)
        self.LocalTableL.customContextMenuRequested['QPoint'].connect(MainWindow.left_local_context)
        self.LocalTableR.customContextMenuRequested['QPoint'].connect(MainWindow.right_local_context)
        self.RemoteTableL.customContextMenuRequested['QPoint'].connect(MainWindow.left_remote_context)
        self.RemoteQuickRefreshButton2.clicked.connect(MainWindow.remote_quick_refresh)
        self.RemoteFullRefreshButton2.clicked.connect(MainWindow.remote_full_refresh)
        self.RemoteFullRefreshButton.clicked.connect(MainWindow.remote_full_refresh)
        self.RemoteQuickRefreshButton.clicked.connect(MainWindow.remote_quick_refresh)
        self.LocalFullRefreshButton.clicked.connect(MainWindow.local_full_refresh)
        self.LocalFullRefreshButton2.clicked.connect(MainWindow.local_full_refresh)
        self.LocalQuickRefreshButton.clicked.connect(MainWindow.local_quick_refresh)
        self.LocalQuickRefreshButton2.clicked.connect(MainWindow.local_quick_refresh)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LocalDirBut.setText(_translate("MainWindow", "Load Directory"))
        self.LocalQuickRefreshButton.setText(_translate("MainWindow", "Quick Refresh"))
        self.LocalFullRefreshButton.setText(_translate("MainWindow", "Full Refresh"))
        self.LeftTab.setTabText(self.LeftTab.indexOf(self.LocalTab), _translate("MainWindow", "Local"))
        self.LocalDirBut_2.setText(_translate("MainWindow", "Load XBMC"))
        self.RemoteQuickRefreshButton2.setText(_translate("MainWindow", "Quick Refresh"))
        self.RemoteFullRefreshButton2.setText(_translate("MainWindow", "Full Refresh"))
        self.LeftTab.setTabText(self.LeftTab.indexOf(self.RemoteTab), _translate("MainWindow", "Remote"))
        self.LeftLoadPlaylistBut.setText(_translate("MainWindow", "Load Playlist"))
        self.pushButton.setText(_translate("MainWindow", "Save Local"))
        self.pushButton_4.setText(_translate("MainWindow", "Save Remote"))
        self.LeftTab.setTabText(self.LeftTab.indexOf(self.PlaylistTab), _translate("MainWindow", "Playlist"))
        self.LocalDirBut_3.setText(_translate("MainWindow", "Load Directory"))
        self.LocalQuickRefreshButton2.setText(_translate("MainWindow", "Quick Refresh"))
        self.LocalFullRefreshButton2.setText(_translate("MainWindow", "Full Refresh"))
        self.RightTab.setTabText(self.RightTab.indexOf(self.LocalTab_2), _translate("MainWindow", "Local"))
        self.LocalDirBut_4.setText(_translate("MainWindow", "Load XBMC"))
        self.RemoteQuickRefreshButton.setText(_translate("MainWindow", "Quick Refresh"))
        self.RemoteFullRefreshButton.setText(_translate("MainWindow", "Full Refresh"))
        self.RightTab.setTabText(self.RightTab.indexOf(self.RemoteTab_2), _translate("MainWindow", "Remote"))
        self.pushButton_7.setText(_translate("MainWindow", "Save Local"))
        self.RightLoadPlaylistBut.setText(_translate("MainWindow", "Load Playlist"))
        self.pushButton_8.setText(_translate("MainWindow", "Save Remote"))
        self.RightTab.setTabText(self.RightTab.indexOf(self.PlaylistTab_2), _translate("MainWindow", "Playlist"))
        self.SyncBut.setText(_translate("MainWindow", "Sync Local and Remote"))
        self.menuPJS_Test.setTitle(_translate("MainWindow", "PJS Test"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

